const log = console.log

const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const days = document.querySelector(".days");
log(days)

const rightArrow = document.querySelector(".next");
rightArrow.addEventListener('click', nextMonth);

const monthYear = document.querySelector("#month-year");
const year = document.querySelector("#year");

var maxFutureMonths = 3;

var today = new Date();

function nextMonth() {
    let curMonth = months.indexOf(monthYear.childNodes[0].textContent);
    log(curMonth);
    let curYear = document.querySelector("#year").innerHTML;
    curMonth++;
    if (curMonth === 12) {
        curMonth = 0;
        curYear++;
    }
    monthYear.childNodes[0].textContent = months[curMonth];
    year.innerHTML = curYear;
    
}




function daysInMonth(month,year) {
  return new Date(year, month, 0).getDate();
}



function makeActive(e) {
    e.preventDefault();
    let curActive = days.querySelector(".active");
    log(curActive);
    log(e.target);
    if (curActive === e.target) {
        return;
    }
    let parent = curActive.parentElement;
    let t = document.createTextNode(parent.childNodes[0].textContent)
    parent.replaceChild(t, curActive);
    curActive.remove();
    let span = document.createElement("span");
    span.setAttribute("class", "active");
    let v = document.createTextNode(e.target.childNodes[0].textContent);
    span.appendChild(v);
    e.target.replaceChild(span, e.target.childNodes[0]);
}

function autoGenerateDates() {
    var totalDays = daysInMonth(today.getMonth() + 1, today.getFullYear());

    for (let i = 1; i < totalDays; i++) {
        let curDay = document.createElement("li");
        var node = document.createTextNode(i)
        curDay.appendChild(node);
        curDay.addEventListener('click', makeActive);
        days.appendChild(curDay);
        if (today.getDate() == i) {
            let span = document.createElement("span");
            span.setAttribute("class", "active");
            var t = document.createTextNode(i);
            span.appendChild(t);
            curDay.innerHTML = "";
            curDay.appendChild(span);
        }
    }
    var m = document.createTextNode(months[today.getMonth()]);
    monthYear.replaceChild(m, monthYear.childNodes[0]);
    let y = document.querySelector("#year");
    y.innerHTML = today.getFullYear();



}

autoGenerateDates();





